export const seedBlueprint = {
  purpose:
    "Future Neon seed plan for DekatLokal P0 demo parity. This file is a blueprint only and is not executed by the demo.",
  requiredScenarios: [
    "culinary-new-user",
    "fast-fashion",
    "returning-service",
    "expired-claim",
    "no-checkup",
    "offline",
    "upload-failure",
    "quiz-failure",
    "reward-eligible",
  ],
  insertOrder: [
    "users",
    "businesses",
    "business_members",
    "learning_preferences",
    "checkup_definitions",
    "checkup_results",
    "checkup_pillar_scores",
    "checkup_claim_tokens",
    "modules",
    "lessons",
    "module_prerequisites",
    "tasks",
    "assessments",
    "assessment_questions",
    "intervention_plans",
    "intervention_plan_steps",
    "module_assignments",
    "lesson_progress",
    "assessment_attempts",
    "task_submissions",
    "business_assets",
    "final_tests",
    "final_test_questions",
    "final_test_attempts",
    "recheckups",
    "certificates",
    "rewards",
    "reward_claims",
    "notifications",
    "audit_events",
  ],
  invariants: {
    dataSourceDefault: "mock",
    primaryPathModuleCount: 3,
    claimTokens: "Store token hashes only. Never store raw opaque claim tokens.",
    completionRule:
      "A required module is complete only after required lessons, passing assessment, and approved or auto-approved task submission.",
    freeModuleOutcome:
      "Every free required module should create at least one reusable Aset Usaha.",
  },
} as const;
